services:
  nql-app:
    stop_grace_period: 30s
    build:
      context: ${PWD}
      target: ${NODE_ENV}
      dockerfile: ${PWD}/src/base/docker/nql-app/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/ping"]
      interval: 10s
      timeout: 120s
      retries: 10
      start_period: 30s
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - MASTRA_DATABASE_URL=${MASTRA_DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - APP_DOMAIN=${APP_DOMAIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - '${PORT}:${PORT}'
