services:
  nql-app:
    stop_grace_period: 30s
    build:
      context: ${PWD}
      target: ${NODE_ENV}
      dockerfile: ${PWD}/src/base/docker/nql-app/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - APP_DOMAIN=${APP_DOMAIN}
    ports:
      - '${PORT}:${PORT}'
