# app-development:
#     container_name: app-development
#     image: app-development
#     build:
#       context: .
#       target: development
#       dockerfile: ./Dockerfile
#     healthcheck:
#       test: nc -z -w 1 localhost 3001
#       interval: 5s
#       timeout: 300s
#       retries: 10
#       start_period: 120s
#     environment:
#       - DATABASE_URI=postgresql://node_api:node_api_password@database-test:5432/node_api
#       - REDIS_URI=redis://redis-test:6379
#       - SESSION_SECRET=F1B875D3993B852E581AA2C537F9D375F55BF52D9582F4578034EB645F7065D0
#     ports:
#       - '3001:3001'
#     # working_dir: /usr/src/app
#     volumes:
#       - .:/usr/src/app
#     # command:
#       # sh -c "yarn config set 'strict ssl' false && yarn && yarn:start:dev"
#     links:
#       - redis-development:redis-development
#       - database-development:database-development
#     depends_on:
#       database-development:
#         condition: service_healthy
#       redis-development:
#         condition: service_healthy
#   app-development:
#     driver: local

