services:
  database-development:
    container_name: 'database-development'
    image: postgres:${POSTGRES_VERSION}
    restart: always
    stop_grace_period: 30s
    healthcheck:
      test: nc -z -w 1 localhost 5432
      interval: 5s
      timeout: 300s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes: 
      - database-development:/var/lib/postgresql/data
  redis-development:
    container_name: redis-development
    image: redis:${REDIS_VERSION}
    restart: always
    stop_grace_period: 30s
    healthcheck:
      test: nc -z -w 1 localhost 6379
      interval: 5s
      timeout: 300s
      retries: 10
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes: 
      - redis-development:/data
  nginx-development:
    image: nginx-development:${NGINX_VERSION}
    container_name: nginx-development
    restart: always
    stop_grace_period: 30s
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ../certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  

volumes:
  database-development:
    driver: local
  redis-development:
    driver: local
