import type { DMMF } from '@prisma/generator-helper';

interface IOptions {
	prismaModel: DMMF.Model;
}

export const getFieldsAndTypes = ({ prismaModel }: IOptions) => {
	const fieldsAndTypes = {};

	const filteredFields = prismaModel.fields.filter((field) => {
		const isScalarField = field.kind === 'scalar';
		const isNotAutoGeneratedField =
			field.name !== 'id' &&
			field.name !== 'createdAt' &&
			field.name !== 'updatedAt';

		return isScalarField && isNotAutoGeneratedField;
	});

	for (let i = 0; i < filteredFields.length; i++) {
		const field = filteredFields[i];

		fieldsAndTypes[field.name] = field.type;
	}

	return fieldsAndTypes;
};
